### ISSUE TITLE
GeoDataFrame.estimate_utm_crs may be useful for reference

### ISSUE THREAD

**Issue by snowman2** [GIS-Consultant/utm-epsg-finder#12]
https://geopandas.readthedocs.io/en/latest/docs/reference/api/geopandas.GeoDataFrame.estimate_utm_crs.html#geopandas.GeoDataFrame.estimate_utm_crs

**Comment by MaxDragonheart** [comment]
Thank you for the reference, I did not know this new feature from the next GeoPandas' release :)
I've developed UTM EPSG Finder a few months ago for solving smart little issues of my working day and some days ago I have decided to make public this work as my first package. My aim is to activate new feature for lines, points and raster as soon as possible.

**Comment by snowman2** [comment]
Sounds good. Glad that you are sharing. For another reference, rioxarray has the same feature for rasters: 
https://corteva.github.io/rioxarray/stable/examples/reproject.html#Reproject-to-UTM

**Comment by MaxDragonheart** [comment]
@snowman2 today I had the opportunity to use `rio.estimate_utm_crs()`. It's a very useful function, thank you for sharing the information :D .
As I said few days ago `utm_epsg_finder` was born to solve my own little problems, I'm relatively new into the Python world. I don't thing to destroy this package for now, it was an useful opportunity for me to learn how is possible create a package. 

Long life to OS :)
